services:
  backend:
    build: ./backend
    ports:
      - "7777:7777"

    develop:
      watch:
        # Sync the working directory with the `/backend` directory in the container
        - action: sync+restart
          path: ./backend
          target: /backend
          ignore:
            - .venv/

        # Rebuild the image if dependencies change by watching uv.lock
        - action: rebuild
          path: ./uv.lock